### ISSUE TITLE
Fails to compile in Unreal 4.13.2

### ISSUE THREAD

**Issue by MightyBOBcnc** [tomlooman/ue4-tutorials#2]
Downloaded the ue4-tutorials repo but can't open the project as it fails to compile for the latest Unreal version.  Output is below: 

```
The project could not be compiled. Would you like to open it in Visual Studio?

Running C:/Program Files (x86)/Epic Games/4.13/Engine/Binaries/DotNET/UnrealBuildTool.exe Tutorials Development Win64 -project="C:/Users/JohnDoe/Documents/Unreal Projects/TomLoomanTutorials 4.13/Tutorials.uproject" -editorrecompile -progress -noubtmakefiles -NoHotReloadFromIDE
@progress push 5%
Parsing headers for TutorialsEditor
  Running UnrealHeaderTool "C:\Users\JohnDoe\Documents\Unreal Projects\TomLoomanTutorials 4.13\Tutorials.uproject" "C:\Users\JohnDoe\Documents\Unreal Projects\TomLoomanTutorials 4.13\Intermediate\Build\Win64\TutorialsEditor\Development\TutorialsEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
Reflection code generated for TutorialsEditor in 3.7660672 seconds
@progress pop
Performing 12 actions (4 in parallel)
[3/12] Resource Tutorials.rc
[2/12] Resource ModuleVersionResource.rc.inl
PCH.Tutorials.h.cpp
UsableCppCharacter.cpp
Tutorials.generated.cpp
TutorialsGameMode.cpp
TutorialsCharacter.cpp
C:\Users\JohnDoe\Documents\Unreal Projects\TomLoomanTutorials 4.13\Source\Tutorials\Private\TutorialsCharacter.cpp(22): error C2248: 'USceneComponent::AttachParent': cannot access private member declared in class 'USceneComponent'
C:\Program Files (x86)\Epic Games\4.13\Engine\Source\Runtime\Engine\Classes\Components/SceneComponent.h(113): note: see declaration of 'USceneComponent::AttachParent'
C:\Program Files (x86)\Epic Games\4.13\Engine\Intermediate\Build\Win64\UE4Editor\Inc\Engine\GameplayStatics.generated.h(24): note: see declaration of 'USceneComponent'
C:\Users\JohnDoe\Documents\Unreal Projects\TomLoomanTutorials 4.13\Source\Tutorials\Private\TutorialsCharacter.cpp(31): error C2248: 'USceneComponent::AttachParent': cannot access private member declared in class 'USceneComponent'
C:\Program Files (x86)\Epic Games\4.13\Engine\Source\Runtime\Engine\Classes\Components/SceneComponent.h(113): note: see declaration of 'USceneComponent::AttachParent'
C:\Program Files (x86)\Epic Games\4.13\Engine\Intermediate\Build\Win64\UE4Editor\Inc\Engine\GameplayStatics.generated.h(24): note: see declaration of 'USceneComponent'
C:\Users\JohnDoe\Documents\Unreal Projects\TomLoomanTutorials 4.13\Source\Tutorials\Private\TutorialsCharacter.cpp(43): warning C4458: declaration of 'InputComponent' hides class member
C:\Program Files (x86)\Epic Games\4.13\Engine\Source\Runtime\Engine\Classes\GameFramework/Actor.h(316): note: see declaration of 'AActor::InputComponent'
C:\Users\JohnDoe\Documents\Unreal Projects\TomLoomanTutorials 4.13\Source\Tutorials\UsableActorTutorial\UsableCppCharacter.cpp(21): error C2248: 'USceneComponent::AttachParent': cannot access private member declared in class 'USceneComponent'
C:\Program Files (x86)\Epic Games\4.13\Engine\Source\Runtime\Engine\Classes\Components/SceneComponent.h(113): note: see declaration of 'USceneComponent::AttachParent'
C:\Program Files (x86)\Epic Games\4.13\Engine\Intermediate\Build\Win64\UE4Editor\Inc\Engine\GameplayStatics.generated.h(24): note: see declaration of 'USceneComponent'
C:\Users\JohnDoe\Documents\Unreal Projects\TomLoomanTutorials 4.13\Source\Tutorials\UsableActorTutorial\UsableCppCharacter.cpp(27): error C2248: 'USceneComponent::AttachParent': cannot access private member declared in class 'USceneComponent'
C:\Program Files (x86)\Epic Games\4.13\Engine\Source\Runtime\Engine\Classes\Components/SceneComponent.h(113): note: see declaration of 'USceneComponent::AttachParent'
C:\Program Files (x86)\Epic Games\4.13\Engine\Intermediate\Build\Win64\UE4Editor\Inc\Engine\GameplayStatics.generated.h(24): note: see declaration of 'USceneComponent'
C:\Users\JohnDoe\Documents\Unreal Projects\TomLoomanTutorials 4.13\Source\Tutorials\UsableActorTutorial\UsableCppCharacter.cpp(61): error C2039: 'LineTraceSingle': is not a member of 'UWorld'
C:\Program Files (x86)\Epic Games\4.13\Engine\Source\Runtime\Engine\Classes\Engine/LocalPlayer.h(18): note: see declaration of 'UWorld'
C:\Users\JohnDoe\Documents\Unreal Projects\TomLoomanTutorials 4.13\Source\Tutorials\UsableActorTutorial\UsableCppCharacter.cpp(127): warning C4458: declaration of 'InputComponent' hides class member
C:\Program Files (x86)\Epic Games\4.13\Engine\Source\Runtime\Engine\Classes\GameFramework/Actor.h(316): note: see declaration of 'AActor::InputComponent'
C:\Users\JohnDoe\Documents\Unreal Projects\TomLoomanTutorials 4.13\Source\Tutorials\Private\TutorialsCharacter.cpp(95): error C2027: use of undefined type 'UAnimInstance'
C:\Program Files (x86)\Epic Games\4.13\Engine\Source\Runtime\Engine\Classes\Animation/AnimBlueprintGeneratedClass.h(15): note: see declaration of 'UAnimInstance'
C:\Users\JohnDoe\Documents\Unreal Projects\TomLoomanTutorials 4.13\Source\Tutorials\Private\TutorialsCharacter.cpp(95): error C2227: left of '->Montage_Play' must point to class/struct/union/generic type
TutorialsProjectile.cpp
TutorialsHUD.cpp
C:\Users\JohnDoe\Documents\Unreal Projects\TomLoomanTutorials 4.13\Source\Tutorials\Private\TutorialsProjectile.cpp(14): error C2664: 'void TBaseDynamicMulticastDelegate<FWeakObjectPtr,void,UPrimitiveComponent *,AActor *,UPrimitiveComponent *,FVector,const FHitResult &>::__Internal_AddDynamic<ATutorialsProjectile>(UserClass *,void (__cdecl ATutorialsProjectile::* )(UPrimitiveComponent *,AActor *,UPrimitiveComponent *,FVector,const FHitResult &),FName)': cannot convert argument 2 from 'void (__cdecl ATutorialsProjectile::* )(AActor *,UPrimitiveComponent *,FVector,const FHitResult &)' to 'void (__cdecl ATutorialsProjectile::* )(UPrimitiveComponent *,AActor *,UPrimitiveComponent *,FVector,const FHitResult &)'
        with
        [
            UserClass=ATutorialsProjectile
        ]
C:\Users\JohnDoe\Documents\Unreal Projects\TomLoomanTutorials 4.13\Source\Tutorials\Private\TutorialsProjectile.cpp(14): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
UsableActor.cpp
Tutorials.cpp
ERROR: UBT ERROR: Failed to produce item: C:\Users\JohnDoe\Documents\Unreal Projects\TomLoomanTutorials 4.13\Binaries\Win64\UE4Editor-Tutorials.dll
Total build time: 39.56 seconds


```

**Comment by jesselawson** [comment]
There are a lot of things that have been changed/depreciated since the original tutorial code was published. I'm working on a compilable, updated version that will come out soon.

**Comment by MightyBOBcnc** [comment]
Thank you!

**Comment by srishti-learner** [comment]
When will be the updated version released?
